name: svix-cli
version: git
summary: A CLI to interact with the Svix API.
description: |
  Svix makes it easy to send webhook from your service while ensuring robust deliverability and a great developer experience for your users. 
  You can think of it as webhooks as a service. https://docs.svix.com/
confinement: strict
base: core18
parts:
  svix-cli:
    plugin: go
    source: .
    source-type: git
    build-packages:
      - gcc
apps:
  svix-cli:
    command: bin/svix-cli
