name: svix-cli
version: git
summary: Svix makes it easy to send webhooks
description: |
  A CLI to interact with the Svix API.
  Svix makes it easy to send webhook from your service while ensuring robust deliverability and a great developer experience for your users. 
  You can think of it as webhooks as a service. https://docs.svix.com/
confinement: devmode
base: core18
parts:
  test-httplab:
    plugin: go
    go-importpath: github.com/svix/svix-cli
    source: .
    source-type: git
    build-packages:
      - gcc
apps:
  test-httplab:
    command: bin/svix-cli
