name: staging

on:
  pull_request:
    branches: [main]
    types: [ edited, assigned, opened, synchronize, reopened ]

permissions:
  contents: write

jobs:
  staging-release:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
                
      - 
        name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1

      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
          
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
