name: validate
on: 
  pull_request:
    branches: [main]
    types: [opened, closed]

  push:
    branches: [ main ]

jobs:
  validate:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        goVer: [1.16.x]

    steps:
      - name: Set up Go ${{ matrix.goVer }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.goVer }}
          
      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1

      # Checks out this ^HEAD from a PR
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: make
        run: |
          make
